---
# tasks file for ansible-jq

- block:
    - name: Install jq packages
      become: yes
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time | default(omit) }}"
        install_recommends: no
      with_items:
        - "{{ jq_packages }}"
        
  become: yes
  tags:
    - jq
    - utilities